### ISSUE TITLE
Large books resulting in "max recursion depth"

### ISSUE THREAD

**Issue by mekarpeles** [deborahgu/abbyy-to-epub3#25]
Generating epub for https://archive.org/details/DTIC_ADA283341 results in max recursion depth:

https://ia601509.us.archive.org/~mek/index.php?id=DTIC_ADA283341&dir=/34/items/DTIC_ADA283341&doc=DTIC_ADA283341&type=epub&debug=true&reCache=1

```
Traceback (most recent call last):
  File "/usr/local/bin/abbyy2epub", line 11, in 
    load_entry_point('abbyy-to-epub3==1.1', 'console_scripts', 'abbyy2epub')()
  File "/usr/local/lib/python3.5/dist-packages/abbyy_to_epub3/parse_abbyy.py", line 39, in add_last_text
    if elem['page_no'] == page:
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by mekarpeles** [comment]
It looks like in `parse_abbyy` we may have to make `add_last_text` iterative to avoid blowing the stacK
